framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

when@local:
    framework:
        mailer:
            envelope:
                recipients: ['fournier.sebastien@outlook.com']

when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['fournier.sebastien@outlook.com']