framework:
    router:
        utf8: true
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(DEFAULT_URI)%'

when@local:
    framework:
        router:
            strict_requirements: true

when@dev:
    framework:
        router:
            strict_requirements: true

when@preprod:
    framework:
        router:
            strict_requirements: null

when@prod:
    framework:
        router:
            strict_requirements: null