framework:
    router:
        utf8: true
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost

when@local:
    framework:
        router:
            strict_requirements: true

when@dev:
    framework:
        router:
            strict_requirements: true

when@preprod:
    framework:
        router:
            strict_requirements: null

when@prod:
    framework:
        router:
            strict_requirements: null