security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            entity:
                class: 'App\Entity\Security\User'
                property: "%env(SECURITY_ADMIN_LOGIN_TYPE)%"
        chain_providers:
            chain:
                providers: [ user_provider ]

    firewalls:

        image_resolver:
            pattern: ^/media/cache/resolve
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/(secure/user|admin-%env(SECURITY_TOKEN)%)
            lazy: true
            provider: user_provider
            form_login:
                login_path: front_index
                check_path: security_login
                username_parameter: "%env(SECURITY_ADMIN_LOGIN_TYPE)%"
                enable_csrf: true
                use_forward: true
                use_referer: true
            switch_user: { role: CAN_SWITCH_USER, parameter: _switch_user }
            http_basic: ~
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                samesite: ~ # possible values: 'strict', 'lax' and null
                remember_me_parameter: '_remember_me'
                always_remember_me: true
                signature_properties: [ password ]
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

        main:
            pattern: ^/
            lazy: true
            provider: chain_providers
            logout:
                path: app_logout
                target: front_index
                invalidate_session: true
            switch_user: { role: CAN_SWITCH_USER, parameter: _switch_user }
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                samesite: ~ # possible values: 'strict', 'lax' and null
                remember_me_parameter: '_remember_me'
                always_remember_me: true
                signature_properties: [ password ]

    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/secure/user', roles: PUBLIC_ACCESS, requires_channel: '%env(SECURE_SCHEME)%' }
        - { path: '^/admin', roles: [ IS_AUTHENTICATED_FULLY, ROLE_ADMIN ], requires_channel: '%env(SECURE_SCHEME)%' }
        - { path: '^/', roles: PUBLIC_ACCESS, requires_channel: '%env(SECURE_SCHEME)%' }