framework:
    default_locale: '%env(APP_LOCALE)%'
    enabled_locales: ['fr']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['%locale%']
        providers:
