controllers:
    resource: ../../src/Controller/
    type: attribute

app_extra:
    resource: .
    type: extra

#base_controller:
#    resource: ../../src/Controller/BaseController.php
#    type: attribute