controllers:
    resource: ../../src/Controller/
    type: attribute

app_extra:
    resource: .
    type: extra

admin_controller:
    resource: ../../src/Controller/Admin/AdminController.php
    type: attribute